<a href="https://colab.research.google.com/github/Apple03244/Colaboratory/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%A0%81%EC%9E%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
X=tf.range(10)

In [ ]:
dataset=tf.data.Dataset.from_tensor_slices(X)

In [ ]:
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
x2={'a':([1,2,3],[4,5,6]),'b':[1,2,3]}
dataset2=tf.data.Dataset.from_tensor_slices(x2)

In [ ]:
for i in dataset2:
  print(i)

{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=1>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=2>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=3>}


## 연쇄변환

In [ ]:
repeat_dataset=dataset2.repeat(3)

In [ ]:
for i in repeat_dataset:
  print(i)

{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=1>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=2>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=3>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=1>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=2>, <tf.Tensor: shape=(), dtype=int32, numpy=5>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=2>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=3>, <tf.Tensor: shape=(), dtype=int32, numpy=6>), 'b': <tf.Tensor: shape=(), dtype=int32, numpy=3>}
{'a': (<tf.Tensor: shape=(), dtype=int32, numpy=1>, <tf.Tensor: shape=(), dtype=int32, numpy=4>), 'b': <tf.Tenso

In [ ]:
batch_dataset=repeat_dataset.batch(4)

In [ ]:
for i in batch_dataset:
  print(i)

{'a': (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 1], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 4], dtype=int32)>), 'b': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 1], dtype=int32)>}
{'a': (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 2], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 4, 5], dtype=int32)>), 'b': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 2], dtype=int32)>}
{'a': (<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>, <tf.Tensor: shape=(1,), dtype=int32, numpy=array([6], dtype=int32)>), 'b': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>}


In [ ]:
drop_batch_dataset=repeat_dataset.batch(4,drop_remainder=True)

In [ ]:
for i in drop_batch_dataset:
  print(i)

{'a': (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 1], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 4], dtype=int32)>), 'b': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 1], dtype=int32)>}
{'a': (<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 2], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 4, 5], dtype=int32)>), 'b': <tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 2], dtype=int32)>}


In [ ]:
apply_drop_batch_dataset=drop_batch_dataset.map(lambda x:x["a"])

In [ ]:
for i in apply_drop_batch_dataset:
  print(i)

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 1], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 5, 6, 4], dtype=int32)>)
(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 1, 2], dtype=int32)>, <tf.Tensor: shape=(4,), dtype=int32, numpy=array([5, 6, 4, 5], dtype=int32)>)


## 데이터 셔플링

경사하강법은 독립적이고 동일한 분포일 때 최고의 성능을 발휘함

따라서 아래와 같이 데이터를 섞는 것은 중요하다

In [ ]:
dataset=tf.data.Dataset.range(10).repeat(2)

In [ ]:
for i in dataset:
  print(i)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [ ]:
shuffle_dataset=dataset.shuffle(buffer_size=4,seed=10).batch(7)

In [ ]:
for i in shuffle_dataset:
  print(i)

tf.Tensor([2 3 5 6 7 4 0], shape=(7,), dtype=int64)
tf.Tensor([1 1 2 0 3 5 9], shape=(7,), dtype=int64)
tf.Tensor([4 7 8 9 6 8], shape=(6,), dtype=int64)


### 샘플링의 한계

1. 완전한 샘플링을 위해선 버퍼의 크기가 데이터 셋의 크기와 같아야한다
2. 메모리 용량보다 큰 데이터 셋은 버퍼가 필연적으로 데이터 셋의 크기보다 작아짐

    -> 따라서 원본 데이터 셋 자체를 섞어야함.
3. 샘플을 더 섞기 위해서 원본 데이터를 여러 파일로 나눈 다음, 훈련하는 동안 랜덤으로 읽는 것.
4. 위의 방법으로도 동일한 파일에 았는 샘플은 함께 처리되기 때문에, 파일 여러개를 랜덤 선택 후 파일에서 동시에 읽은 레코드를 돌아가면서 반환

### step 1. 여러 파일에서 한줄씩 번갈아 읽기

In [ ]:
file_paths=['/content/train.csv' for i in range(3)]

In [ ]:
file_paths

['/content/train.csv', '/content/train.csv', '/content/train.csv']

In [ ]:
shuffle_paths=tf.data.Dataset.list_files(file_paths,seed=10)

위는 파일경로를 섞는 과정

In [ ]:
dataset=shuffle_paths.interleave(
    lambda x:tf.data.TextLineDataset(x).skip(1) #맨 윗줄은 columns 이름이므로
    ,cycle_length=2 # 한번에 두개의 파일을 한줄씩 번갈아가면서 읽음
    ,num_parallel_calls=tf.data.AUTOTUNE # 병렬화 개수 -> 자동화
)

* 과정 요약

1. 파일 경로 데이터 셋
2. interleave 메소드 내의 lambda 함수로 인해 병력처리된 데이터셋들
3. 위의 데이터셋을 돌아가면서 한줄씩 적재한 interleave dataset